# docker-compose.yml
app:
  build: ./
  volumes:
    - ./:/dist
  ports:
    - 3000:3000
  environment:
    - NODE_ENV=development
    - PORT=3000
    - MONGO_URL="mongodb://localhost:27017/unu"
    - MONGO_COLLECTION="parking"
  command:
    sh -c 'npm i && node index.js'