# docker-compose.yml
version: "2"

services:
  web:
    build: .
    links: 
      - mongo
    volumes:
      - ./dist:/service/dist
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGO_URL=mongodb://mongo:27017/unu
      - MONGO_DB=unu
      - MONGO_COLLECTION=parking
  mongo:
    image: mongo:latest
    volumes:
      - mongodata:/data/db
volumes:
  mongodata: